# Licensed to ObjectStyle LLC under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ObjectStyle LLC licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

jdk:
  - openjdk8
  - oraclejdk11
  - openjdk-ea

script:
  - mvn clean verify

jobs:
  include:
    - stage: deploy
      jdk: openjdk8
      script: mvn clean source:jar javadoc:javadoc deploy -DskipTests --settings travis_settings.xml
      if: branch IN (master) AND type IN (push) AND repo = bootique/bootique-cxf

# travis encrypt -r bootique/bootique-cxf "CI_DEPLOY_USERNAME='name'"
#   password'"
env:
  global:
    - secure: "TW5NmvkiUYNHuoiQ0KTsG9SYI61nMuWgguqrvm2PMO9aVxlx+VyM58W8u2b/LB73nzC7zqyfhUQsumYlUGiO/JUGtm3C7VifJso1MW3a+PtpDFNkgy3MV8dbXKBDzKmJLKQ02EjxTMAW+xdid67aB7/e5k7t++zEtqFHmeZTPofi+Ix+pDQnxY0GYOxzbVOWalvRSVjpgSWIenyFM4K9433StWYHxgJ1Xqyc0iuMDXLqOBQK6f0m4JW/enr1EIOnkaTnnP5JTo3vhoyt8GGOp4xoglLx9ejgf+JaEMe8aGjgkBIUUxnSunkcFqGl7QWPWy0mG8OE2Ra4E7Zo3gTM9QKnn9q32n0CZi1SR+F3aszebiMvk/uSj3y1fCUjl43xXlp0Roy17oz5rqMH4+wsX6I6dMPsrMwPRjZlOlLNIJjwRAkZCZAPsQFUVu6VVsTQsB3M2tIAgfaojGKCVwhAiF5SWBm9Aiq5UlQaRF8rWs3CCfi4Az2cXAK4GpOqbiS27jrGZygNWd7RevsgR1fWM/dzA0UIp1WaW+VspOMx+mXxhowm4jYwng1+uLQglfbQa67HY1l/TMP0DYbTR42VXTqG+7392K8AeL8VHVEcwEELDaY5JG674iUMaPi9JB3bqdFgWeeTwciQ2nPGBTfat937Pg8EFoOuwt0nYc5PYUY="
    - secure: "ov5QiggSWobOTgU9jTi6vWo8xNVQHlthrD4y9GtcmicPg/CbCCHdp48XnrId+dH5ipTtFuxImcV0hMTEh695HL/oAOu66ir1QXiD+4dgGzZaJWVSqh0BI9tX8l8JRsQgwdZ5NSF/6P3G5jqtzqlNYscCJpgBnZFvu6yi6yktWXX7dicgd1t1JXGrFv1vcrOVVl5F12CJ7dDc9hME6jO5ehB3GBs9VdCbiZ8hBBS4vgfNzFYESWPGcaphYEcI5cCrA9vsoHfIIUozds+vPRt6hr6zRJvDh1Jbiou7pTCgFda6EdbZtFkACdQFSkLgsVcSu4xd2i05AA1bvByTNlLWJMkeILMM7WU4qS5K8w4WrXyTzTXn22j5P3jBtHC3rwuVV4tVLLT0Uiy1AF4ZlPOGpXrzDUggE1YkbZj816LAeweNkx54zUjRObu0qBAi9BIFcgRSSdNCGX7D1i1RIgqaRiw5GP4KLSMO5hGvbBXXEk7uZgP8jVy6VkXSbbOUEYK8+utAQiN9G5Ovbt4G15nNSgBggbXdDVUbwkyir8fa0tVlscz9Uo/3j6bDwCgABOPjUvyQYPLujE2TckwsBQS1oHxPe9TvUZ9N6KSEYk3xYNNxig73qHHYZe3WwSPg3iiE2iZOzXoXYnCsWVggwBEEugHsFFaaUVrVfoYKaBO9nLU="
