# Licensed to ObjectStyle LLC under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ObjectStyle LLC licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

jdk:
  - openjdk8
  - oraclejdk11
  - openjdk-ea

script:
  - mvn clean verify

jobs:
  include:
    - stage: deploy
      jdk: openjdk8
      script: mvn clean source:jar javadoc:javadoc deploy -DskipTests --settings travis_settings.xml
      if: branch IN (master) AND type IN (push) AND repo = bootique/bootique-cxf

# travis encrypt -r bootique/bootique-cxf "CI_DEPLOY_USERNAME='name'"
#   password'"
env:
  global:
    - secure: "lU1kZ5UIlHjDUkT29xdg7o8JngjqtwZJE4fzY6CpgEkNq+t30sVOL/vWjonzYulgTbeX6TmOeod0SgzRFygKzoBC3bM6k2q0MNRN2LfpExP+3re1/K1CrTIemAA9PC8g6vXcqEHsoJsgkT6zfDuXGVOD6DMCKP1z9obpfxkKYLF/+KBSmKxAiOKmnGrvgJ7j0hmP60LOhBbNb5U0xZ3SQGzbJwadytewq7n/qCkm8EdgbT0v7VMhkdbx5tRXylJjsjay7pCdK4kUEaC9NjgAaD0MBe8BajTRXwxChROdSG9/ttYA+7uFMUyOx85R7HqA8A8DLDWhnV4kBvOwTfO8vz7LJzfitITfGa4+NHf4AikEM6lpMmoQR8eeo+RgUolGVRrR5DfeiseQk4FBsevJioz2zy78SKFGb+M1tx2RrrViJ4QkGxhboQPyq0Olv6mUei/oPA9xNDtbmhCauJtgg/hEWLG/2U2nu17EJnCt2E2RHx0ujm5Ec0nzaWQ32Gymw5fYnMl5hEtl4/9lQz2FJULLFpMtbVgB6MpaiFFej25seMp+aMHrWMFY287BETGvHIDqPd0UgGq3CIN838Sau9Q1OvegY3Ph1aMW0a1erqgXAeMaI3mqGBVtBAJq4lch/qz/YIRQpQ7BJ3KSZZio5YvolJ5EPkPY5vMwZmpWupA="
    - secure: "Ea2QCutk7i7lg3dk/KeAXhaqan72zzCLsmL7PgGdOZHnIPpKKdPLRbum0OBCeVJOBA1NRTyq9JdIwgRugBejDs2hJeF0YnxOn5feaBCqjw1vsj3YOjz58b9bbZz5PCJTZch4BRKkhJyS1U39wIHr9cz63K1XcsgfuUOEs+9O+unB641IHfHaQyF0xZ5fSU63OSZJOr8Es3D/WM/hlAJL4PpxXKXZkngU8pCxPg42xjtIQdvbkh3FaO4AeEf+CaVeKO0xkCeIXmEz/VUnLYBatj1YlMUqMt0jejbdPQIXVPLwyiF0CWTc6RoWRHENrxBk/WBkOYqneOvmCDPuEbcASc1y1SKJ0Jov2flPnhzzwX6kmrDi+7C01BND2/Gk4cjYx0+xHACrTogaUkeTo/L8Bksbbprp0Ije2u0fePIBwYYbJ1WnWs3pdhWOizgVNqf/Wg8Vl3CKhFgIwLAq8FTVud8jxOeXMxj6U8aIG28SpJ7Z1eT2Txj45NC77Uvh3+GiRrdbJw/omR5w2Q8AqI/3BVT5ncJofpsTpDUU+dEO897/oGAukzz7DYmcy15pAy6znkaVvOIb7kLr7E36hx3dl4y+Yx/B3+c4007HETr/DA9y11IkbvuZrPNvrSyxh9XBuwgvQ7qxoqzi3eMAz8O7E7fyEy/MakRBDvGLrSerpKQ="
